### ISSUE TITLE
JobType enum

### ISSUE THREAD

**Issue by lucaro** [vitrivr/cthulhu#4]
The type of a job should probably be represented using an enum, since there will be a fixed set of existing types.

**Comment by pabloem** [comment]
I'm a bit stuck on this. Here's the issue:
It would make sense to have an enum for job types, but our data exchange format is JSON. Since we want to serialize all this data to be able to recover in case the workers or the master are killed, we will be writing a bunch of JSON to hard drive - and I figured it would be nice if it was human-readable. Does this make sense?

Now let me elaborate with JSON-design issues:

Actually, I am not sure what JSON library to use. I looked at GSON and Jackson but I don't like that they lack some flexibility (what if a job has more attributes than just those defined in a class?), so I'm using json-minimal like you guys do in Cineast.

By using JsonObject as the internal representation, we end up with something that is easy to serialize, but it is a bit awkward at times (see the [new Job class](https://github.com/vitrivr/cthulhu/blob/master/src/org/vitrivr/cthulhu/jobs/Job.java)' getter methods).

If we used a JSON-POJO library it would make serialization easy and coding less awkward, but we might lose flexibility. What's your take on this?

**Comment by lucaro** [comment]
I wouldn't use jsonobjects as internal storage objects but rather build a static serialize and deserialize method. The serialize function transform a job object into a json-encoded string while the deserialize method would be a factory creating job-objects from json-strings. I don't really see an issue with using an existing library like GSON or Jackson to do this...

The primary reason why cineast uses json-minimal was that it was easy to extend the parser in order to add an additional stop symbol ';' so it would return when reading from a stream without the stream having to be closed. I also quite like the API...

**Comment by pabloem** [comment]
Alright! I've switched to GSON for Job creation. I solved the 'flexibility' problem by creating a custom serializer/deserializer so that each job type can be serialized/deserialized properly. Job type will take the name of the classes (e.g. "BashJob", "FeatureExtractionJob", "Job", etc.)
